### ISSUE TITLE
Skip log-in screen when running a test in a brand-new hive?

### ISSUE THREAD

**Issue by OmerRaviv** [Microsoft/VisualStudio-TestHost#24]
Whenever you launch Visual Studio in a new hive, you get this screen: 
![image](https://cloud.githubusercontent.com/assets/641292/16169637/65fa05e4-353e-11e6-8a54-2fd263c398da.png)

Is there any way for an integration test to skip this or otherwise automate pressing the "Not now, maybe later" link? It's been a bit of a pain to have to do this on every new machine your tests run on. Perhaps VisualStudio-TestHost should even do this by default?

**Comment by zooba** [comment]
It's difficult to detect when we should do it, unfortunately, and it interferes with some of the timeouts that are part of it.

I use this powershell snippet in my setup script to run it after installation:

``` powershell
"Resetting settings to avoid prompt on first run"
$p = Start-Process -PassThru "$path\Common7\IDE\devenv.exe" -ArgumentList "/resetsettings", "$path\Common7\IDE\Profiles\General.vssettings"
while ($p -and -not ($p.HasExited -or ($p.MainWindowTitle -match "^Start Page"))) {
    Sleep -Seconds 5;
    $p.Refresh()
}
try {
    $p.CloseMainWindow();
    $p.WaitForExit();
} catch [Exception] {
    Write-Error $_ -EA Continue
}
"Settings reset"
""
```

**Comment by zooba** [comment]
Looks like it may be easier to pass `/Command File.Exit` to devenv rather than the loop that I've used here. Haven't tested it yet though.

**Comment by zooba** [comment]
Confirming that I've now been using (and recommend) this command for setting up the new hive:

``` powershell
Start-Process -Wait "$path\Common7\IDE\devenv.exe" `
    -ArgumentList "/resetsettings", `
        """$path\Common7\IDE\Profiles\General.vssettings""", `
        "/command", "File.Exit"
```

(where `$path` is the root of the VS install)
