### ISSUE TITLE
"HostType" could not be found after execution of PowerShell install script

### ISSUE THREAD

**Issue by cbries** [Microsoft/VisualStudio-TestHost#35]
Hello, I just tried to use this extension but within Unittest-files I only get the following errors:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'HostTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)	UnitTestProject5	C:\temp\UnitTestProject5\UnitTestProject5\UnitTest1.cs	10	Active
Error	CS0246	The type or namespace name 'HostType' could not be found (are you missing a using directive or an assembly reference?)	UnitTestProject5	C:\temp\UnitTestProject5\UnitTestProject5\UnitTest1.cs	10	Active`

Have a look on the screenshot.
Within PowerShell not install error occur.
The testsettings files are provided VS' install directory, the dlls are there as well.

But in VS the HostType is unknown.

What should I do?

![2018-08-20 12_16_23-c__program files x86 _microsoft visual studio_2017_professional_common7_ide_com](https://user-images.githubusercontent.com/5418062/44334829-e4ffda80-a472-11e8-8499-0591f672bfc9.png)

![2018-08-20 12_14_39-c__program files x86 _microsoft visual studio_2017_professional](https://user-images.githubusercontent.com/5418062/44334743-b1bd4b80-a472-11e8-9fd4-da938849e397.png)

![missing types in unittest-project](https://user-images.githubusercontent.com/5418062/44334744-b1bd4b80-a472-11e8-869b-4c9aad802980.png)

![powershellinstallof-vstesthost](https://user-images.githubusercontent.com/5418062/44334746-b255e200-a472-11e8-9b46-78cadc260eff.png)

Looks installed:
![installed extensions](https://user-images.githubusercontent.com/5418062/44335198-fd242980-a473-11e8-8a0c-57b34921488e.png)

**Comment by zooba** [comment]
You'll need to reference `Microsoft.VisualStudio.QualityTools.UnitTestFramework` as well to get that attribute (see https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.hosttypeattribute.aspx)

**Comment by cbries** [comment]
Cheers @zooba, in case of adding the mentioned reference I just get messages about ambiguous calls. Have a look:
![image](https://user-images.githubusercontent.com/5418062/44440837-3a9acb00-a5ca-11e8-8680-c41189271057.png)
The UnitTest-tpls provided by VS17 has been changed by Microsoft.

I remove "Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions" and Intellisense looks fine.
But than I just getting the following exception which I already mentioned in the other issue (see #36 , I will give the workaround a try) **The test adapter ('Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') required to execute this test could not be loaded.** 

![image](https://user-images.githubusercontent.com/5418062/44440900-86e60b00-a5ca-11e8-874e-3d186bbb1142.png)

As a conclusion... This issue looks ok for me and could be closed. It was not clear for me how to conquer all this to install the testadapter, because of the fact VisualStudio 17 updates have some internal changes and it is not easy to find out which problematic was born for getting third-party libraries to run.
