### ISSUE TITLE
The test adapter ('Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') required to execute this test could not be loaded. 

### ISSUE THREAD

**Issue by cbries** [Microsoft/VisualStudio-TestHost#36]
When I try to run the simple tests of the attached solution, I always get:

The test adapter ('Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') required to execute this test could not be loaded. 

![image](https://user-images.githubusercontent.com/5418062/44340739-0b7b4100-a486-11e8-910f-2cccce53bff1.png)

[UnitTestProject2.zip](https://github.com/Microsoft/VisualStudio-TestHost/files/2302350/UnitTestProject2.zip)

My VS version is:

![image](https://user-images.githubusercontent.com/5418062/44340753-1f26a780-a486-11e8-8851-5d3cbdd3e9c9.png)

**Comment by zooba** [comment]
@sailro - any ideas? I haven't been using VSTestHost in recent VS releases, so not sure if something has changed.

**Comment by sailro** [comment]
Yes, for several releases, the Test platform extension broke assembly resolution... I already created a bug for that, this should be resolved with 15.9.x

As a workaround you can try the following (this is what we are doing currently for our UI testing):

In ```[VS Studio Path]\Common7\IDE\Extensions\TestPlatform```:

Create symbolic links to PrivateAssemblies and PublicAssemblies with the following (as admin):
```mklink /D PrivateAssemblies ..\..\PrivateAssemblies```
```mklink /D PublicAssemblies ..\..\PublicAssemblies```

Still in In ```[VS Studio Path]\Common7\IDE\Extensions\TestPlatform```:
Create a Folder ```CommonExtensions\Platform```, and copy ```Microsoft.VisualStudioTools.VSTestHost.15.0.dll``` into it.

And make sure that you used the latest ```InstallInVS2017.ps1``` to install the test adapter, so that we are properly patching all configuration files.

Seb

**Comment by cbries** [comment]
Amazing.

Thanks @sailro .

With the currently latest version of **InstallInVS2017.ps1** (I have used this version 4c5f2b7 on Feb 2) and your mentioned additional steps for a workaround work like a charm and the exceptions vanished.

As an additiontal hint for other people.
You have to set the testsettings file, otherwise incorrect paths are used for executing the devenv.exe.

Without the testsettings file:
`TestContext Messages:
Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe"
Failed to launch devenv.exe (VisualStudio, 15.0)
Restarting VS
Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe"
Failed to launch devenv.exe (VisualStudio, 15.0)`

With one of the provided testsettings file in **C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional**
![image](https://user-images.githubusercontent.com/5418062/44441739-79328480-a5ce-11e8-94b7-cbb8e8498cdf.png)

![image](https://user-images.githubusercontent.com/5418062/44441751-8c455480-a5ce-11e8-85f5-c11b22d6e653.png)

You will get:
![image](https://user-images.githubusercontent.com/5418062/44441783-aa12b980-a5ce-11e8-9927-f2179287438a.png)

**Comment by cbries** [comment]
Thanks

**Comment by rsuk** [comment]
I have hit this issue and followed the instructions to create the symbolic links and use the right .testsettings file, but I am still seeing this as the result of my test runs (tried my own project and the example at the start of this issue):

> Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe"
> Failed to launch devenv.exe (VisualStudio, 15.0)
> Restarting VS
> Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe"
> Failed to launch devenv.exe (VisualStudio, 15.0)

Anyone have any ideas for what I can try / where I can look?
