### ISSUE TITLE
Issue launching a test in VS 2017 - "Failed to launch devenv.exe"

### ISSUE THREAD

**Issue by rsuk** [Microsoft/VisualStudio-TestHost#37]
I'm experiencing the issue described in Issue #36 (now closed). After following the patch instructions on that issue, I get the following test result output (VS is never launched):

> TestContext Messages: Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe" Failed to launch devenv.exe (VisualStudio, 15.0) Restarting VS Launching VisualStudio: "...\Microsoft Visual Studio 15.0\Common7\IDE\devenv.exe" Failed to launch devenv.exe (VisualStudio, 15.0)

I have carefully followed the instructions to create the symbolic links and am using the right .testsettings file, but I am still seeing this as the result of my test runs (tried my own project and the example at the start of this issue):

Anyone have any ideas for what I can try / where I can look?

**Comment by sailro** [comment]
What is your VS 2017 version ?

**Comment by Enache-Ionut** [comment]
The same thing on my machine. I am using the latest Visual Studio 2017 v.15.9.10. The attribute `HostType` is now deprecated. Maybe this is the issue.

**Comment by sailro** [comment]
I added workarounds for assembly resolution issues for both VS 2017 and VS 2019 in installer scripts.

We are using this successfully with latest VS versions.

See:

https://github.com/Microsoft/VisualStudio-TestHost/commit/42fbbb64d38c1cc54ac21a5041922bb07940b028

and

https://github.com/Microsoft/VisualStudio-TestHost/commit/a1978127320dedce924ce598a2265c399b17129a
