### ISSUE TITLE
Create Gitter room

### ISSUE THREAD

**Issue by sharwell** [Microsoft/VisualStudio-TestHost#4]
Can you create a gitter.im room for this repository by any chance, similar to what the roslyn/corefx/coreclr teams have done?

**Comment by zooba** [comment]
Sure, why not. It's at https://gitter.im/Microsoft/VisualStudio-TestHost

Looks like I can't enable the webhooks because I don't really own this repo. Is that something that's really important? I haven't used gitter.im before.

**Comment by sharwell** [comment]
It's nice, but not required. If you try to configure the webhook through Gitter, there is a section for "Manual" configuration. It will give you a key that you can copy and send to the internal team that actually owns this repository, and they can configure the webhook for you from the GitHub side.
