### ISSUE TITLE
Support per-test VS launch settings

### ISSUE THREAD

**Issue by zooba** [Microsoft/VisualStudio-TestHost#6]
Currently we load VS settings from the run settings (`*.testsettings` file), but properties can also be applied to individual tests:

``` csharp
[TestMethod]
[TestProperty("VSVersion", "12.0")]
[HostType("VSTestHost")]
```

We should add the logic required to re-evaluate the required VS instance for each test based on the test properties, restarting the instance if necessary.

I don't think it's possible to re-order tests to group ones with matching properties, so having lots of different tests in the same class may not be a good idea for performance, but for small projects it'll be more convenient than dealing with multiple separate files.

**Comment by zooba** [comment]
Unfortunately, it turns out that you can't actually run tests in versions of VS different from the one you're launching them from, so while this now works (in my branch), it's only good for choosing between Express editions and hives, which is not very useful.

**Comment by sharwell** [comment]
Do you know what the limiting factor is that prevents you from running tests in a different version?

**Comment by zooba** [comment]
Breaking changes within the test framework. The info about the test class and method is private to the UnitTest class, but it can marshal between processes as ITestElement. But because the class is different between versions (and VS has assembly binding redirects for lower versions and no back-compat for higher versions), you can't marshal the test object between different versions.
