### ISSUE TITLE
Port helper class from PTVS

### ISSUE THREAD

**Issue by zooba** [Microsoft/VisualStudio-TestHost#8]
For PTVS we use [helper classes](https://github.com/Microsoft/PTVS/tree/master/Common/Tests/Utilities.UI/UI) for interacting with Visual Studio.

We should port the core pieces of this functionality into VSTestHost so that people do not need to reimplement it themselves.

**Comment by zooba** [comment]
We should lazily create the helper class on a property access via VSTestContext, then ensure that everything is disposed at the end of the test (since we control the test adapter). That way people get appropriate functionality with less boilerplate code (no `using...`), and can also opt-out for particular tests.

**Comment by sharwell** [comment]
At minimum we should create two solution files to handle this (the alternative is creating a separate repository). The assemblies which get installed in the GAC and build outputs getting placed in the Visual Studio folders will make users not want to build this project themselves, but they'll likely want to contribute to the portions used for mocking the environment and/or helpers to interact with the environment.

**Comment by zooba** [comment]
Good point. Perhaps a Nuget package with the helpers makes more sense than embedding it into the GAC'd portion.

Though I still think there's a bare minimum that makes sense to lock down, and we've been using these wrappers long enough that we can commit to the interfaces. That'll make building on top of them much easier.

**Comment by OmerRaviv** [comment]
+1 on this being a two different solution files and possibly having the helpers as a NuGet package.
I've been working on compiling PTVS just so I could get started with VisualStudio-TestHost.

**Comment by zooba** [comment]
You should be able to pull out the TestUtilities projects fairly easily and avoid having to build all the rest of PTVS. (In fact, if you do that and merge them into one project, we'd happily take it as a PR to this repo :) )

**Comment by OmerRaviv** [comment]
OK great, I'm working on this - I'll create a "VSTestUtilities" folder in this repo with a separate .sln file and we could then ship all the test utilities via NuGet as you requested.

**Comment by OmerRaviv** [comment]
Couple of questions here:
1. In PTVS, the Build mechanism builds everything separately for each version of VS. I'm assuming we don't need this in this repro, and just aim for the TestUtilities NuGet to work against VS2012 (or hopefully VS2010) and up?
2. In TestUtilities.csproj, we have a `USE_PYTHON_TESTDATA` preprocessor flag defined, and [this code](https://github.com/Microsoft/PTVS/blob/0a3d9d17008e8d9b8fe2cb40c6c501f13861ccdb/Common/Tests/Utilities/SharedProject/SharedProjectTest.cs#L48-L52) inside `SharedProjectTest.cs`. Since this repro should not have any Python specific things, I'll need to delete this snippet and flag. I'm assuming that once my PR is in, we'll want to avoid the duplication and delete the utilities from PTVS  and instead consume them via NuGet. How would you like me to handle this?

**Comment by OmerRaviv** [comment]
3 . Regarding your statement:

> We should lazily create the helper class on a property access via VSTestContext, then ensure that everything is disposed at the end of the test (since we control the test adapter).That way people get appropriate functionality with less boilerplate code (no using...), and can also opt-out for particular tests.

That would require that we add a direct dependency from VSTestHost->VSTestUtilities. Perhaps an easier way of instructing people to properly dispose the helper class at the end of each test is to just include Project Templates inside of the VSIX with proper sample code?

**Comment by zooba** [comment]
> 1 . In PTVS, the Build mechanism builds everything separately for each version of VS.

Afraid we'll still need separate builds for each VS version, as the point of many of the helpers is to hide VS-version specific differences (look at the REPL window classes, for example). They could theoretically be built with a single version of VS (and different sets of reference assemblies), but I don't think they can be combined into one assembly for all VS versions.

That said, it might be possible to have a single assembly that users link to and then load the correct one at runtime.

BTW, I think VS 2010 is right out of the picture, due to limitations of the test framework. But feel free to find a workaround for that :)

> 2 . In TestUtilities.csproj, we have a `USE_PYTHON_TESTDATA` preprocessor flag defined, and this code inside `SharedProjectTest.cs`

The point of this code is to handle implicit deployment dependencies. PTVS builds 20+ DLLs, but they are loosely coupled and so the test adapter doesn't know to deploy them. SharedProjectTest uses MEF on its current directory to implicitly load the code that generates either PTVS or NTVS projects.

FWIW, I don't think these really need to be kept for a shared utilities project. They're fairly unreliable tests anyway, and building new project systems is specialized enough that people would probably rather have more control. I know I'd rather have more control...

> 2b. I'm assuming that once my PR is in, we'll want to avoid the duplication and delete the utilities from PTVS and instead consume them via NuGet. How would you like me to handle this? 

Don't worry about that for now - there's a lot of churn going on in PTVS and you've got basically no chance of keeping parallel PRs going.

Just make the best possible utilities for other people to use and we can change PTVS later.

> 3 . include Project Templates inside of the VSIX with proper sample code?

Probably an item template for a unit test class that already has the first few `using (var app = new VisualStudioApp()) { // Test goes here }` filled in would be enough. A project template wouldn't be useless either, but in my experience the project already exists when I decide I want something like this.

**Comment by zooba** [comment]
@huguesv, @int19h and a few others are also interested in splitting these out, so you may want to collaborate on that sooner. Those guys have permissions to this repo, so feel free to create a branch here and work out of that until it's ready to merge.

(Also, @OmerRaviv, I checked out OzCode and it's _very_ nice. What would it take to get https://github.com/Microsoft/PTVS support? :) )

**Comment by int19h** [comment]
I'll be switching to work on this item basically full time (until it's done) at the end of this month.

**Comment by OmerRaviv** [comment]
Cool! I'm currently only working on this PR as part of a consultancy gig one day out of the week, hence the delay, but I should make some good progress this week and I'll give you guys an update so we could collaborate and get it done quicker.

@zooba Thanks so much! Would love to get it (or at least the basic features like Reveal and Search) working for PTVS and branch out to other languages (F#, VB.NET, JS, etc) as well, just need to get enough C# people to buy it (or at least be aware that it exists :)) so we could afford the continued effort.

**Comment by OmerRaviv** [comment]
Apologies for the delay. I just submitted #18. 

The first commit was just moving the files over from PTVS and just getting it to compile. I intentionally avoided squashing the rest of my changes into a single commit so that you could conveniently review them. 

I kept the build script for VSTestUtilities separate from VSTestHost, let me know what you think!

I didn't address versioning and publishing of the NuGet packages - how would you like to handle this? 

Also, I didn't get around to adding Item/Project Templates just yet.
